FROM python:3.12-slim@sha256:e5c9fa26ffb76e11e0f054f30dc2523a2f9693f0c36c0cf1e39b27e152d899fc

# UV_COMPILE_BYTECODE=1  -> Force uv to pre-compile .py source files to .pyc bytecode
# Docker builds may take a few seconds longer, but the containerized application will start up significantly faster.
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    UV_COMPILE_BYTECODE=1 

WORKDIR /app

RUN pip install --no-cache-dir uv

COPY requirements.txt ./
RUN uv pip install --system --no-cache -r requirements.txt

COPY config.py custom_logger.py fastapi_app.py ./
COPY src ./src

RUN mkdir -p /app/data

EXPOSE 8000

CMD ["uvicorn", "fastapi_app:app", "--host", "0.0.0.0", "--port", "8000"]